version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      
  test:
    post:
      - curl -sSL https://download.sourceclear.com/ci.sh | sh
